services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jarvis_helpdesk_plugins_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: "unless-stopped"
    networks:
      - jarvis-plugin-network


  nginx:
    image: nginx:latest
    volumes:
      - ./data/nginx/jarvis-helpdesk-plugin-api.conf.template:/etc/nginx/templates/jarvis-helpdesk-plugin-api.conf.template
      - ./data/nginx/jarvis-helpdesk-admin.conf.template:/etc/nginx/templates/jarvis-helpdesk-admin.conf.template
      - ./data/nginx/jarvis-helpdesk-ai-module.conf.template:/etc/nginx/templates/jarvis-helpdesk-ai-module.conf.template
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - jarvis-plugin-network
    env_file:
      - ./.env.nginx
    depends_on:
      - certbot
      - jarvis-helpdesk-plugins-api
    entrypoint: >
      /bin/bash -c "
      for template in /etc/nginx/templates/*.template; do
        envsubst < $$template > /etc/nginx/conf.d/$$(basename $${template%.*}).conf;
      done;
      while :; do
        sleep 6h & wait $${!};
        nginx -s reload;
      done &
      nginx -g 'daemon off;'
      "

  jarvis-helpdesk-admin:
    build:
      context: ../jarvis-helpdesk-plugins
      dockerfile: Dockerfile
      args:
        - ENV_FILE_PATH=./.env.admin
    restart: "unless-stopped"
    networks:
      - jarvis-plugin-network
    ports:
      - "8888:8888"

  jarvis-helpdesk-plugins-api:
    build:
      context: ../jarvis-helpdesk-plugins-api
      dockerfile: Dockerfile
    restart: "unless-stopped"
    networks:
      - jarvis-plugin-network
    env_file:
      - ./.env.plugin-api
    depends_on:
      - postgres
    expose:
      - 5555

  jarvis-helpdesk-ai-module:
    build:
      context: ../jarvis-helpdesk-ai-module
      dockerfile: Dockerfile
    restart: "unless-stopped"
    networks:
      - jarvis-plugin-network
    env_file: ./.env.ai-module
    expose:
      - 5502

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres-data:

networks:
  jarvis-plugin-network:
    driver: bridge
